title: LeoJhon.Song's Blog
subtitle: 欢迎来到我的博客!
description: 记 / 录 / 与 / 分 / 享
keywords: null
author: LeoJhon.Song
language: zh-CN
timezone: null
url: 'https://leojhonsong.github.io/zh-CN'
root: /zh-CN
permalink: ':title/'
permalink_defaults: null
source_dir: source/zh-CN
public_dir: public/zh-CN
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
auto_spacing: true
titlecase: true
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 0
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: LeoJhonSong
deploy:
  type: git
  repo: 'git@github.com:LeoJhonSong/zh-CN.git'
  branch: master
server:
  compress: true
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
symbols_count_time:
  symbols: true
  time: false
  total_symbols: true
  total_time: false
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true
google_site_verification: MgaZs4EoTDqCTCMVBOft2UKu2g6AfLiKx2VTQ_KBeH4
valine:
  lang: zh-cn
