#! /usr/bin/python3

import os
import sys


# ################################layer2 functions##############################
os.chdir(sys.path[0])
def prepare():
    os.system('cp themes/LeoJhonSong/asset/post_asset.js node_modules/hexo/lib/models/post_asset.js')

def generateDeployEnglish():
    generateEnglish()
    deployEnglish()


def generateEnglish():
    prepare()
    os.system('hexo clean')
    os.system('hexo g')


def deployEnglish():
    os.system('hexo d')


def serverEnglish():
    os.system('hexo s')


def generateDeployChinese():
    generateChinese()
    deployChinese()


def generateChinese():
    prepare()
    os.system('hexo clean --config _config.yml,_config.zh-CN.yml')
    os.system('hexo g --config _config.yml,_config.zh-CN.yml')


def deployChinese():
    os.system('hexo d --config _config.yml,_config.zh-CN.yml')


def serverChinese():
    os.system('hexo server --config _config.yml,_config.zh-CN.yml')


# ################################layer1 functions##############################
def generateDeployAll():
    generateDeployEnglish()
    generateDeployChinese()


def english():
    layer2 = {
        'default': generateDeployEnglish,
        'g': generateEnglish,
        'd': deployEnglish,
        's': serverEnglish
    }
    child = layer2[sys.argv[2] if len(sys.argv) > 2 else 'default']
    child()


def chinese():
    layer2 = {
        'default': generateDeployChinese,
        'g': generateChinese,
        'd': deployChinese,
        's': serverChinese
    }
    child = layer2[sys.argv[2] if len(sys.argv) > 2 else 'default']
    child()


def newEnglish():
    os.system('hexo new ' + ' '.join(sys.argv[2:]))


def newChinese():
    os.system('hexo new ' + ' '.join(sys.argv[2:]) + ' --config _config.yml,_config.zh-CN.yml')

def clean():
    os.system('hexo clean')


layer1 = {
    'default': generateDeployAll,
    'e': english,
    'c': chinese,
    'ne': newEnglish,
    'nc': newChinese,
    # 'na': newAll,
    'clean': clean
}
# ##############################################################################

# add hexo to PATH
os.environ['PATH'] = os.path.abspath('.') + '/node_modules/hexo/bin/' + ':' + os.environ['PATH']

# the main process
main = layer1[sys.argv[1] if len(sys.argv) > 1 else 'default']
main()
