name: English Blog Site CI

on:
  push:
    branches:
      - Root
    paths-ignore:
      - 'source/zh-CN/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.10.0
      uses: actions/setup-node@v1
      with:
        node-version: 8.10.0
    - name: npm install and modify
      run: |
        npm install
        cp themes/LeoJhonSong/asset/post_asset.js node_modules/hexo/lib/models/post_asset.js
    - name: login ssh and git
      env:
        id_rsa_github_action: ${{ secrets.id_rsa_github_action }}
      run: |
        mkdir ~/.ssh
        echo -e "Host github.com\nStrictHostKeyChecking no\nIdentityFile ~/.ssh/id_rsa_github_action" > ~/.ssh/config
        echo -e "$id_rsa_github_action" > ~/.ssh/id_rsa_github_action
        chmod 600 ~/.ssh/id_rsa_github_action
        git config --global user.email "LeoJHon.Song@outlook.com"
        git config --global user.name "GitHub Action"
    - name: Generate and deploy English site
      run: |
        rm -rf .deploy_git
        git clone -b master git@github.com:LeoJhonSong/LeoJhonSong.github.io.git .deploy_git
        ./a e
