name: English Blog Site CI

on:
  push:
    branches:
      - Root
    paths:
      - 'source/en/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.10.0
      uses: actions/setup-node@v1
      with:
        node-version: 8.10.0
    - name: Generate and deploy English site if necessary
      run: |
        rm -rf .deploy_git
        git clone -b master https://github.com/LeoJhonSong/LeoJhonSong.github.io.git .deploy_git
        ./a e
