name: Chinese Blog Site CI

on:
  push:
    branches:
      - Root
    paths-ignore:
      - 'source/en/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.10.0
      uses: actions/setup-node@v1
      with:
        node-version: 8.10.0
    - name: npm install, install pandoc and set timezone
      run: |
        npm install
        sudo apt install -y pandoc
        sudo timedatectl set-timezone Asia/Shanghai
    - name: login ssh and git
      env:
        id_rsa_github_action: ${{ secrets.id_rsa_github_action }}
      run: |
        mkdir ~/.ssh
        echo -e "Host github.com\nStrictHostKeyChecking no\nIdentityFile ~/.ssh/id_rsa_github_action" > ~/.ssh/config
        echo -e "$id_rsa_github_action" > ~/.ssh/id_rsa_github_action
        chmod 600 ~/.ssh/id_rsa_github_action
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "gitHub-actions"
    - name: Generate and deploy Chinese site
      run: |
        rm -rf .deploy_git
        git clone -b master git@github.com:LeoJhonSong/zh-CN.git .deploy_git
        ./a c
